### ISSUE TITLE
Task expired when last read information is pulled

### ISSUE THREAD

**Issue by gustavoqzdaa** [gustavoqzdaa/ute_energy#3]
In some cases, a request to retrieve last reading info from Ute API might expire and return empty values.

`2023-05-10 14:59:15.387 DEBUG (SyncWorker_2) [custom_components.ute_energy.ute_energy] Retrieve latest reading info return status: 200, content: {'data': {'timestamp': '2023-05-10T14:59:06.226644', 'statusText': 'ERROR DE LECTURA DEL MEDIDOR', 'status': 4, 'readings': [{'tipoLecturaMGMI': 'V1', 'valor': '', 'fechaHora': '10/05/2023 14:58:01'}, {'tipoLecturaMGMI': 'I1', 'valor': '', 'fechaHora': '10/05/2023 14:58:01'}, {'tipoLecturaMGMI': 'RELAY_ON', 'valor': '', 'fechaHora': '10/05/2023 14:58:01'}], 'lastQueryDate': '2023-05-10T14:47:08.680665', 'lastResponseDate': '2023-05-10T14:59:06.226644', 'informationStatus': 2, 'error': 'task expired'}, 'result': 0, 'messages': [], 'success': True, 'errors': []}
2023-05-10 14:59:15.390 ERROR (MainThread) [custom_components.ute_energy.coordinator] Unexpected error fetching ute_energy data: could not convert string to float: ''
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/ute_energy/coordinator.py", line 56, in _async_update_data
    data = await self._service_account_data()
  File "/config/custom_components/ute_energy/coordinator.py", line 67, in _service_account_data
    response = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ute_energy/ute_energy.py", line 190, in retrieve_service_account_data
    data.update(self._retrieve_latest_reading_info(account_id))
  File "/config/custom_components/ute_energy/ute_energy.py", line 324, in _retrieve_latest_reading_info
    current_power = float(data[CURRENT_VOLTAGE]) * float(
ValueError: could not convert string to float: ''`

**Comment by gustavoqzdaa** [comment]
Fixed in the last release
