### ISSUE TITLE
Retrieve info from UTE API return empty values

### ISSUE THREAD

**Issue by gustavoqzdaa** [gustavoqzdaa/ute_energy#4]
In some cases, a request to retrieve info from Ute API might return empty values.

`2023-05-11 01:32:00.252 DEBUG (SyncWorker_2) [custom_components.ute_energy.ute_energy] Retrieve service agreement return status: 200, content: {'data': None, 'result': 1, 'messages': [], 'success': False, 'errors': []}
2023-05-11 01:32:00.256 ERROR (MainThread) [custom_components.ute_energy.coordinator] Unexpected error fetching ute_energy data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/ute_energy/coordinator.py", line 56, in _async_update_data
    data = await self._service_account_data()
  File "/config/custom_components/ute_energy/coordinator.py", line 67, in _service_account_data
    response = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ute_energy/ute_energy.py", line 184, in retrieve_service_account_data
    data = self._retrieve_service_agreement(account_id)
  File "/config/custom_components/ute_energy/ute_energy.py", line 199, in _retrieve_service_agreement
    agreement_info = content[DATA][AGREEMENT_INFO]
TypeError: 'NoneType' object is not subscriptable`

**Comment by gustavoqzdaa** [comment]
Fixed in the last release
