### ISSUE TITLE
BUG: No device or entities

### ISSUE THREAD

**Issue by krabbi** [gustavoqzdaa/ute_energy#7]
After initialization there's no added entites. And there's repeating Errors in the LOG
```
2023-06-18 10:52:13.932 WARNING (MainThread) [homeassistant.config_entries] Config entry 'XXXXXXXXX' for ute_energy integration not ready yet: max() arg is an empty sequence; Retrying in background
2023-06-18 11:07:03.783 DEBUG (MainThread) [custom_components.ute_energy.coordinator] Data will be update every 0:10:00
2023-06-18 11:07:04.099 DEBUG (SyncWorker_8) [custom_components.ute_energy.ute_energy] Retrieve service agreement return status: 200, content: {'data': {'agreementInfo': {'serviceAgreementId': 'XXXXXXXXX', 'department': 'MALDONADO', 'city': 'MALDONADO', 'address': 'MALDONADO', 'zipCode': '20000-XXXXXX', 'contractedPowerOnPeak': 3.5, 'contractedPowerOnValley': None, 'contractedPowerOnFlat': None, 'tariff': 'TRD', 'zone': 'MALDONADO', 'commercialOffice': 'OFICINA COMERCIAL I MALDONADO', 'voltage': 'BT 230 V', 'serviceType': 'MONOFASICO', 'consumption': []}, 'meterInfo': {'saId': 'XXXXXXXXX', 'premiseDescription': 'MALDONADO', 'spId': 'XXXXXXXXXX', 'mtrId': 'XXXXXXXXX', 'saStatus': 20, 'amiPresent': True, 'agreementType': 'Eléctrico Particular', 'tariffDescription': 'Tarifa Residencial Doble Horario', 'tariffType': 'DOBLE', 'amiType': 'KAIFA'}}, 'result': 0, 'messages': [], 'success': True, 'errors': []}
2023-06-18 11:07:04.137 DEBUG (SyncWorker_8) [custom_components.ute_energy.ute_energy] Verify tariff peak selection available return status: 200, content: {'result': 24, 'messages': [], 'success': False, 'errors': [{'id': '9', 'text': 'El usuario y/o contraseña ingresada no son válidas. Utilice su usuario web o deshabilite ésta opción', 'detail': 'InvalidCredentials'}]}
2023-06-18 11:07:04.186 DEBUG (SyncWorker_8) [custom_components.ute_energy.ute_energy] Retrieve latest invoice info return status: 200, content: {'data': {'invoices': [], 'totalDebt': 0.0}, 'result': 0, 'messages': [], 'success': True, 'errors': []}
2023-06-18 11:07:04.188 ERROR (MainThread) [custom_components.ute_energy.coordinator] Unexpected error fetching ute_energy data: max() arg is an empty sequence
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ute_energy/coordinator.py", line 57, in _async_update_data
    data = await self._service_account_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ute_energy/coordinator.py", line 68, in _service_account_data
    response = await self.hass.async_add_executor_job(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ute_energy/ute_energy.py", line 187, in retrieve_service_account_data
    data.update(self._retrieve_latest_invoice_info(account_id))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ute_energy/ute_energy.py", line 256, in _retrieve_latest_invoice_info
    latest_invoice = self._extract_latest_invoice_info(invoices)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ute_energy/ute_energy.py", line 272, in _extract_latest_invoice_info
    last_invoice = max(
                   ^^^^
ValueError: max() arg is an empty sequence
2023-06-18 11:07:04.195 DEBUG (MainThread) [custom_components.ute_energy.coordinator] Finished fetching ute_energy data in 0.411 seconds (success: False)
```
<img width="293" alt="image" src="https://github.com/gustavoqzdaa/ute_energy/assets/5084613/504cf431-a303-4524-94b8-db0208759cab">
<img width="1257" alt="Screenshot 2023-06-18 at 11 04 49" src="https://github.com/gustavoqzdaa/ute_energy/assets/5084613/a4be59e1-8598-499d-8d2b-21daaf865a77">

Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.2

**Comment by gustavoqzdaa** [comment]
This issue is due to the empty invoices of this service account. Fixed in the last release.

**Comment by krabbi** [comment]
@gustavoqzdaa Thank you, it resolved that problem, but new one raised on the same step
```
2023-06-18 13:38:32.119 DEBUG (MainThread) [custom_components.ute_energy.coordinator] Data will be update every 0:10:00
2023-06-18 13:38:32.272 DEBUG (SyncWorker_1) [custom_components.ute_energy.ute_energy] Retrieve service agreement return status: 200, content: {'data': {'agreementInfo': {'serviceAgreementId': 'XXXXXXXXX', 'department': 'MALDONADO', 'city': 'MALDONADO', 'address': 'MALDONADO', 'zipCode': '20000-XXXXX', 'contractedPowerOnPeak': 3.5, 'contractedPowerOnValley': None, 'contractedPowerOnFlat': None, 'tariff': 'TRD', 'zone': 'MALDONADO', 'commercialOffice': 'OFICINA COMERCIAL I MALDONADO', 'voltage': 'BT 230 V', 'serviceType': 'MONOFASICO', 'consumption': []}, 'meterInfo': {'saId': 'XXXXXXXXX', 'premiseDescription': MALDONADO', 'spId': 'XXXXXXXXX', 'mtrId': 'XXXXXXXXX', 'saStatus': 20, 'amiPresent': True, 'agreementType': 'Eléctrico Particular', 'tariffDescription': 'Tarifa Residencial Doble Horario', 'tariffType': 'DOBLE', 'amiType': 'KAIFA'}}, 'result': 0, 'messages': [], 'success': True, 'errors': []}
2023-06-18 13:38:32.307 DEBUG (SyncWorker_1) [custom_components.ute_energy.ute_energy] Verify tariff peak selection available return status: 200, content: {'result': 24, 'messages': [], 'success': False, 'errors': [{'id': '9', 'text': 'El usuario y/o contraseña ingresada no son válidas. Utilice su usuario web o deshabilite ésta opción', 'detail': 'InvalidCredentials'}]}
2023-06-18 13:38:32.342 DEBUG (SyncWorker_1) [custom_components.ute_energy.ute_energy] Retrieve latest invoice info return status: 200, content: {'data': {'invoices': [], 'totalDebt': 0.0}, 'result': 0, 'messages': [], 'success': True, 'errors': []}
2023-06-18 13:38:32.378 DEBUG (SyncWorker_1) [custom_components.ute_energy.ute_energy] Retrieve latest consumption return status: 200, content: {'data': None, 'result': 0, 'messages': [], 'success': True, 'errors': [{'id': '9', 'text': 'El usuario y/o contraseña ingresada no son válidas. Utilice su usuario web o deshabilite ésta opción', 'detail': 'InvalidCredentials'}]}
2023-06-18 13:38:32.379 ERROR (MainThread) [custom_components.ute_energy.coordinator] Unexpected error fetching ute_energy data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ute_energy/coordinator.py", line 57, in _async_update_data
    data = await self._service_account_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ute_energy/coordinator.py", line 68, in _service_account_data
    response = await self.hass.async_add_executor_job(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ute_energy/ute_energy.py", line 188, in retrieve_service_account_data
    data.update(self._retrieve_latest_month_consumption_info(account_id))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ute_energy/ute_energy.py", line 290, in _retrieve_latest_month_consumption_info
    active_consumption = content[DATA][0][ACTIVE_CONSUMPTION][SINGLE_SERIE]
                         ~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2023-06-18 13:38:32.384 DEBUG (MainThread) [custom_components.ute_energy.coordinator] Finished fetching ute_energy data in 0.264 seconds (success: False)
```

**Comment by gustavoqzdaa** [comment]
I will add more validations.
For some reason, it returns an invalid credential error. Can you check if you can access the invoices in the official UTE app?
Other than that, can you try removing the integration and adding it again?

Just to find out where this invalid credential error is coming from.

**Comment by krabbi** [comment]
Oops, looks like it's my mistake. I didn't finalize registering in UTE App. After I've added password - everything works.
Thank you, integration is amazing
