### ISSUE TITLE
Error on integration setup

### ISSUE THREAD

**Issue by RenzoBeux** [gustavoqzdaa/ute_energy#9]
After setting this integration i have this error

![image](https://github.com/gustavoqzdaa/ute_energy/assets/47984043/d9b21260-74af-473a-82cd-a078d3230781)

And this is the log output error
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ute_energy/__init__.py", line 48, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ute_energy/coordinator.py", line 57, in _async_update_data
    data = await self._service_account_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ute_energy/coordinator.py", line 68, in _service_account_data
    response = await self.hass.async_add_executor_job(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError: aiohttp connection lost
```

**Comment by gustavoqzdaa** [comment]
Seems this is a connection issue, enable debug mode for the integration, try reconfiguring and provide the new logs.
